<?php
/**
 * Return Request Email Order Items Template
 *
 * @category    Narvar
 * @package     Narvar_ConnectEE
 *
 * @author      premkumarsankar premkumar.sankar@aspiresys.com
 * @copyright   Copyright (c) 2012-2019 Narvar Inc
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $orderItems = $block->getOrderItems(); ?>
<table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Item Name')); ?>
                </th>
                <th class="item-info">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Sku')); ?>
                </th>
                <th class="item-info">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Return Qty')); ?>
                </th>
                <th class="item-info">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Reason')); ?>
                </th>
                <th class="item-info">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Item Condition')); ?>
                </th>
                <th class="item-info">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Resolution')); ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($orderItems as $orderItem) :?>
                <tr>
                    <td class="item-info">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('%1', $orderItem['name']))?>
                    </td>
                    <td class="item-info">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('%1', $orderItem['item_sku']))?>
                    </td>
                    <td class="item-info">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('%1', $orderItem['qty']))?>
                    </td>
                    <td class="item-info">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('%1', $orderItem['reason']))?>
                    </td>
                    <td class="item-info">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('%1', $orderItem['condition']))?>
                    </td>
                    <td class="item-info">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml(__('%1', $orderItem['resolution']))?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
</table>